---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: runtime-
resources:
  - pod.yaml
images:
  - name: runtime-workbench
    newName: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-intel-tensorflow-notebook
    newTag: runtime-test
configMapGenerator:
  - name: req-config
    files:
      - requirements-elyra.txt
